### ISSUE TITLE
Doesnt work for me

### ISSUE THREAD

**Issue by karldanninger** [Commander147/CMStorm#1]
Followed the README, double clicked the app after adding it to the privacy & security portion, then nothing

**Comment by Commander147** [comment]
@kdanninger 
Do you see the app running in the system dock at the top right of the screen? 
Should see CM: on/off?

**Comment by karldanninger** [comment]
nope i dont! but, somehow the keyboard started lighting up after playing around with other workarounds!

Thanks anyway for your hard work....

Perhaps this isn't compatible with OSX 10.11?

I'll close this issue since the keyboard and all modes seem to work within it's own firmware
