### ISSUE TITLE
Don't show in top panel

### ISSUE THREAD

**Issue by hikinine** [Commander147/CMStorm#3]
First thank you for the project.

I followed steps to install your software 
![image](https://user-images.githubusercontent.com/30875229/148127459-bc581332-29ca-416f-a15e-267d4041890c.png)

give enough perms (accessibility and keyboard monit)
![image](https://user-images.githubusercontent.com/30875229/148127506-be3a1bda-c517-4a88-99b3-83bf25cdc90c.png)

but looks like nothing is happening. Already restart my computer and reinstall things but still not working. 
then I tried to search inside the project

/CMStorm.app/Contents/MacOS/CMStorm
![image](https://user-images.githubusercontent.com/30875229/148127650-2fd0cd2d-00c8-46d5-a989-3c8cd0edf7bf.png)

/Applications/CMStorm.app/Contents/MacOS/CMStorm ; exit;
➜  ~ /Applications/CMStorm.app/Contents/MacOS/CMStorm ; exit;
[1]    2374 segmentation fault  /Applications/CMStorm.app/Contents/MacOS/CMStorm

**2374 segmentation fault**
am I doing something wrong?

MacOS Catalina 10.15.7 version

**Comment by toybz** [comment]
I also experienced this, are you able to resolve the issue @hikinine
